#!/usr/bin/env python3
import sys, os, shutil
VERSION = "1.1"
TARGET_PATH = "/etc/polkit-1/rules.d/90-custom-ui.rules"
def validate(path):
    if not os.path.exists(path): return False
    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
            return "polkit.addRule" in content or "Generated by Polkit Policy Editor" in content
    except: return False
def main():
    if len(sys.argv) < 3: sys.exit(1)
    cmd, src = sys.argv[1], sys.argv[2]
    if cmd == "write":
        if not validate(src): sys.exit(2)
        try:
            tmp = TARGET_PATH + ".new"
            shutil.copyfile(src, tmp); os.chmod(tmp, 0o644); os.rename(tmp, TARGET_PATH)
            print("Policy updated.")
        except Exception as e: print(e); sys.exit(3)
if __name__ == "__main__": main()
